<?php
include 'Conex.php';

mysqli_select_db ($enlace, $nombreBD);

$tabla1="CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR VARCHAR(20) PRIMARY KEY,
     NOMBRE_PROVEEDOR VARCHAR(30),
     CIF_EMPRESA VARCHAR(12) NOT NULL,
     NUMERO_TELEFONO varchar(9)
     
     
 
 );";

 mysqli_query ($enlace, $tabla1);

$tabla2="CREATE TABLE PRODUCTO (
    ID_PRODUCTO VARCHAR(10) PRIMARY KEY,
    NOMBRE_PRODUCTO VARCHAR(30) NOT NULL,
    MARCA_PRODUCTO VARCHAR(20),
    PRECIO VARCHAR(20),
    CANTIDAD INTEGER(20),
    ESTADO VARCHAR(20),
    ID_PROVEEDOR VARCHAR(20),
    FOREIGN KEY ID_PROVEEDOR(ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR)
    

);";

mysqli_query ($enlace, $tabla2);

$tabla3="CREATE TABLE PEDIDOS (
    ID_PEDIDO VARCHAR(20) PRIMARY KEY,
    DESCRIPCION VARCHAR (69) NOT NULL,
    FECHA VARCHAR (10),
    TOTAL VARCHAR (50),
    ID_PRODUCTO VARCHAR(10),
    FOREIGN KEY ID_PRODUCTO(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
    
  
    
);";

mysqli_query ($enlace, $tabla3);

$tabla4="CREATE TABLE CLIENTES (
    ID_CLIENTE VARCHAR(20) PRIMARY KEY,
    DNI VARCHAR (9) NOT NULL,
    TRATO VARCHAR (10),
    NOMBRE VARCHAR (50),
    TELEFONO varchar (9),
    CORREO VARCHAR(50),
    TIPO VARCHAR(10),
    ID_PEDIDO VARCHAR(20),
    FOREIGN KEY ID_PEDIDO(ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)

    
);";
mysqli_query ($enlace, $tabla4);

mysqli_close ($enlace);
?>